# Generated by Django 4.2.11 on 2025-11-30 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FleetAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("total_drones", models.IntegerField()),
                ("active_drones", models.IntegerField()),
                ("drones_in_flight", models.IntegerField()),
                ("drones_in_maintenance", models.IntegerField()),
                ("total_orders", models.IntegerField()),
                ("pending_orders", models.IntegerField()),
                ("completed_orders", models.IntegerField()),
                ("failed_orders", models.IntegerField()),
                (
                    "avg_delivery_time_minutes",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "avg_eta_accuracy_percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "total_distance_km",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "avg_battery_level",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("low_battery_count", models.IntegerField(default=0)),
                (
                    "fleet_uptime_percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Fleet Analytics",
                "verbose_name_plural": "Fleet Analytics",
                "db_table": "fleet_analytics",
                "get_latest_by": "timestamp",
                "indexes": [
                    models.Index(
                        fields=["timestamp"], name="fleet_analy_timesta_f51d82_idx"
                    )
                ],
            },
        ),
    ]
