# Generated by Django 4.2.11 on 2025-11-30 07:17

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OperationalZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "boundary",
                    django.contrib.gis.db.models.fields.PolygonField(
                        geography=True,
                        help_text="Polygon defining the operational zone",
                        srid=4326,
                    ),
                ),
                (
                    "altitude_min",
                    models.DecimalField(
                        decimal_places=2, default=0, help_text="meters", max_digits=6
                    ),
                ),
                (
                    "altitude_max",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="meters",
                        max_digits=6,
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        limit_choices_to={"role__in": ["admin", "manager"]},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Operational Zone",
                "verbose_name_plural": "Operational Zones",
                "db_table": "operational_zone",
                "indexes": [
                    models.Index(
                        fields=["is_active"], name="operational_is_acti_4ef36b_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="NoFlyZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "zone_type",
                    models.CharField(
                        choices=[
                            ("airport", "Airport"),
                            ("military", "Military"),
                            ("government", "Government"),
                            ("private", "Private Property"),
                            ("weather", "Weather Hazard"),
                            ("temporary", "Temporary Restriction"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "boundary",
                    django.contrib.gis.db.models.fields.PolygonField(
                        geography=True,
                        help_text="Polygon defining the no-fly zone",
                        srid=4326,
                    ),
                ),
                (
                    "altitude_min",
                    models.DecimalField(
                        decimal_places=2, default=0, help_text="meters", max_digits=6
                    ),
                ),
                (
                    "altitude_max",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="meters",
                        max_digits=6,
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("valid_from", models.DateTimeField(blank=True, null=True)),
                ("valid_until", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        limit_choices_to={"role__in": ["admin", "manager"]},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "No-Fly Zone",
                "verbose_name_plural": "No-Fly Zones",
                "db_table": "no_fly_zone",
                "indexes": [
                    models.Index(
                        fields=["is_active", "zone_type"],
                        name="no_fly_zone_is_acti_b8fa42_idx",
                    ),
                    models.Index(
                        fields=["valid_from", "valid_until"],
                        name="no_fly_zone_valid_f_4f4b95_idx",
                    ),
                ],
            },
        ),
    ]
