# Generated by Django 4.2.11 on 2025-11-30 07:17

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DeliveryOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pickup_address", models.TextField()),
                (
                    "pickup_location",
                    django.contrib.gis.db.models.fields.PointField(
                        geography=True, srid=4326
                    ),
                ),
                ("delivery_address", models.TextField()),
                (
                    "delivery_location",
                    django.contrib.gis.db.models.fields.PointField(
                        geography=True, srid=4326
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("assigned", "Assigned to Drone"),
                            ("in_transit", "In Transit"),
                            ("delivering", "Out for Delivery"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("assigned_at", models.DateTimeField(blank=True, null=True)),
                ("picked_up_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("estimated_eta", models.DateTimeField(blank=True, null=True)),
                ("actual_delivery_time", models.DateTimeField(blank=True, null=True)),
                (
                    "priority",
                    models.IntegerField(
                        default=1, help_text="Higher number = higher priority"
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Delivery Order",
                "verbose_name_plural": "Delivery Orders",
                "db_table": "delivery_order",
            },
        ),
        migrations.CreateModel(
            name="OrderStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(max_length=20)),
                ("notes", models.TextField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Order Status History",
                "verbose_name_plural": "Order Status Histories",
                "db_table": "order_status_history",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Package",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "package_type",
                    models.CharField(
                        choices=[
                            ("document", "Document"),
                            ("food", "Food"),
                            ("medical", "Medical"),
                            ("electronics", "Electronics"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(decimal_places=2, help_text="kg", max_digits=6),
                ),
                (
                    "dimensions_length",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="cm",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "dimensions_width",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="cm",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "dimensions_height",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="cm",
                        max_digits=6,
                        null=True,
                    ),
                ),
                ("is_fragile", models.BooleanField(default=False)),
                ("is_urgent", models.BooleanField(default=False)),
                ("requires_temperature_control", models.BooleanField(default=False)),
                (
                    "temperature_range",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Package",
                "verbose_name_plural": "Packages",
                "db_table": "package",
            },
        ),
    ]
