# Generated by Django 4.2.11 on 2025-11-30 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("deliveries", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("drones", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderstatushistory",
            name="changed_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="orderstatushistory",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="status_history",
                to="deliveries.deliveryorder",
            ),
        ),
        migrations.AddField(
            model_name="deliveryorder",
            name="customer",
            field=models.ForeignKey(
                limit_choices_to={"role": "customer"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="deliveryorder",
            name="drone",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deliveries",
                to="drones.drone",
            ),
        ),
        migrations.AddField(
            model_name="deliveryorder",
            name="package",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order",
                to="deliveries.package",
            ),
        ),
        migrations.AddIndex(
            model_name="orderstatushistory",
            index=models.Index(
                fields=["order", "timestamp"], name="order_statu_order_i_fa0797_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="deliveryorder",
            index=models.Index(
                fields=["status", "customer"], name="delivery_or_status_7a0119_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="deliveryorder",
            index=models.Index(
                fields=["drone", "status"], name="delivery_or_drone_i_b7d712_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="deliveryorder",
            index=models.Index(
                fields=["requested_at"], name="delivery_or_request_87f10b_idx"
            ),
        ),
    ]
