# Generated by Django 4.2.11 on 2025-11-30 07:17

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("deliveries", "0001_initial"),
        ("drones", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DroneStatusStream",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_online", models.BooleanField(default=False)),
                ("last_heartbeat", models.DateTimeField(blank=True, null=True)),
                (
                    "connection_quality",
                    models.IntegerField(
                        default=100, help_text="0-100, connection quality percentage"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "current_mission",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="status_streams",
                        to="deliveries.deliveryorder",
                    ),
                ),
                (
                    "drone",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_stream",
                        to="drones.drone",
                    ),
                ),
            ],
            options={
                "verbose_name": "Drone Status Stream",
                "verbose_name_plural": "Drone Status Streams",
                "db_table": "drone_status_stream",
            },
        ),
        migrations.CreateModel(
            name="TelemetryData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "position",
                    django.contrib.gis.db.models.fields.PointField(
                        geography=True, srid=4326
                    ),
                ),
                (
                    "altitude",
                    models.DecimalField(
                        decimal_places=2, help_text="meters", max_digits=6
                    ),
                ),
                (
                    "heading",
                    models.DecimalField(
                        decimal_places=2, help_text="degrees", max_digits=5
                    ),
                ),
                (
                    "speed",
                    models.DecimalField(
                        decimal_places=2, help_text="km/h", max_digits=6
                    ),
                ),
                ("battery_level", models.IntegerField()),
                (
                    "battery_voltage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "temperature",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "wind_speed",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "wind_direction",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("is_in_flight", models.BooleanField(default=True)),
                ("gps_signal_strength", models.IntegerField(blank=True, null=True)),
                (
                    "drone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="telemetry_data",
                        to="drones.drone",
                    ),
                ),
            ],
            options={
                "verbose_name": "Telemetry Data",
                "verbose_name_plural": "Telemetry Data",
                "db_table": "telemetry_data",
                "get_latest_by": "timestamp",
                "indexes": [
                    models.Index(
                        fields=["drone", "timestamp"],
                        name="telemetry_d_drone_i_44e256_idx",
                    ),
                    models.Index(
                        fields=["timestamp"], name="telemetry_d_timesta_914397_idx"
                    ),
                ],
            },
        ),
    ]
