# Generated by Django 4.2.11 on 2025-11-30 07:17

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Drone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("model", models.CharField(max_length=100)),
                ("manufacturer", models.CharField(max_length=100)),
                (
                    "max_payload_weight",
                    models.DecimalField(decimal_places=2, help_text="kg", max_digits=6),
                ),
                (
                    "max_speed",
                    models.DecimalField(
                        decimal_places=2, help_text="km/h", max_digits=6
                    ),
                ),
                (
                    "max_altitude",
                    models.DecimalField(
                        decimal_places=2, help_text="meters", max_digits=6
                    ),
                ),
                (
                    "max_range",
                    models.DecimalField(decimal_places=2, help_text="km", max_digits=6),
                ),
                (
                    "battery_capacity",
                    models.DecimalField(
                        decimal_places=2, help_text="mAh", max_digits=6
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("idle", "Idle"),
                            ("charging", "Charging"),
                            ("assigned", "Assigned to Delivery"),
                            ("delivering", "Delivering"),
                            ("returning", "Returning to Base"),
                            ("maintenance", "Under Maintenance"),
                            ("offline", "Offline"),
                        ],
                        db_index=True,
                        default="idle",
                        max_length=20,
                    ),
                ),
                (
                    "battery_level",
                    models.IntegerField(default=100, help_text="Percentage"),
                ),
                (
                    "current_position",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, geography=True, null=True, srid=4326
                    ),
                ),
                (
                    "current_altitude",
                    models.DecimalField(
                        decimal_places=2, default=0, help_text="meters", max_digits=6
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_heartbeat", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Drone",
                "verbose_name_plural": "Drones",
                "db_table": "drone",
            },
        ),
        migrations.CreateModel(
            name="MaintenanceLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "maintenance_type",
                    models.CharField(
                        choices=[
                            ("routine", "Routine"),
                            ("repair", "Repair"),
                            ("upgrade", "Upgrade"),
                            ("inspection", "Inspection"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("scheduled_at", models.DateTimeField()),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "drone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_logs",
                        to="drones.drone",
                    ),
                ),
            ],
            options={
                "verbose_name": "Maintenance Log",
                "verbose_name_plural": "Maintenance Logs",
                "db_table": "maintenance_log",
            },
        ),
    ]
