# Generated by Django 4.2.11 on 2025-11-30 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("drones", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="maintenancelog",
            name="performed_by",
            field=models.ForeignKey(
                limit_choices_to={"role__in": ["admin", "manager"]},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="drone",
            index=models.Index(
                fields=["status", "is_active"], name="drone_status_31d01c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="drone",
            index=models.Index(
                fields=["serial_number"], name="drone_serial__a6a9cc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="maintenancelog",
            index=models.Index(
                fields=["drone", "scheduled_at"], name="maintenance_drone_i_90096f_idx"
            ),
        ),
    ]
