# Generated by Django 4.2.11 on 2025-11-30 07:17

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("deliveries", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "path",
                    django.contrib.gis.db.models.fields.LineStringField(
                        geography=True,
                        help_text="Optimized route path as LineString",
                        srid=4326,
                    ),
                ),
                (
                    "total_distance",
                    models.DecimalField(
                        decimal_places=2, help_text="km", max_digits=10
                    ),
                ),
                ("estimated_duration", models.IntegerField(help_text="minutes")),
                ("estimated_eta", models.DateTimeField()),
                (
                    "confidence_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="AI model confidence (0-100)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "optimization_method",
                    models.CharField(
                        default="astar",
                        help_text="Algorithm used (astar, dijkstra, rl)",
                        max_length=50,
                    ),
                ),
                ("avoids_no_fly_zones", models.BooleanField(default=True)),
                ("avoids_weather_hazards", models.BooleanField(default=True)),
                (
                    "altitude_profile",
                    models.JSONField(
                        default=dict, help_text="Altitude changes along route"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "delivery_order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="optimized_route",
                        to="deliveries.deliveryorder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Route",
                "verbose_name_plural": "Routes",
                "db_table": "route",
            },
        ),
        migrations.CreateModel(
            name="Waypoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence", models.IntegerField(help_text="Order in route sequence")),
                (
                    "position",
                    django.contrib.gis.db.models.fields.PointField(
                        geography=True, srid=4326
                    ),
                ),
                (
                    "altitude",
                    models.DecimalField(
                        decimal_places=2, help_text="meters", max_digits=6
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        default="waypoint",
                        help_text="pickup, waypoint, delivery, avoid",
                        max_length=50,
                    ),
                ),
                ("estimated_arrival", models.DateTimeField(blank=True, null=True)),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="waypoints",
                        to="routes.route",
                    ),
                ),
            ],
            options={
                "verbose_name": "Waypoint",
                "verbose_name_plural": "Waypoints",
                "db_table": "waypoint",
                "ordering": ["route", "sequence"],
                "indexes": [
                    models.Index(
                        fields=["route", "sequence"], name="waypoint_route_i_0e4252_idx"
                    )
                ],
                "unique_together": {("route", "sequence")},
            },
        ),
        migrations.AddIndex(
            model_name="route",
            index=models.Index(
                fields=["estimated_eta"], name="route_estimat_12d01a_idx"
            ),
        ),
    ]
